using System.Collections.Generic;
using System.Windows.Input;


namespace Androidplayer_wpf.Src.Android;



public static class AndroidKeyCode_store
    {
        public static readonly Dictionary<Key, AndroidKeyCode> ModifierKeyMap = new()
        {
            // Shift / Ctrl / Alt
            { Key.LeftShift, AndroidKeyCode.ShiftLeft },
            { Key.RightShift, AndroidKeyCode.ShiftRight },
            { Key.LeftCtrl, AndroidKeyCode.CtrlLeft },
            { Key.RightCtrl, AndroidKeyCode.CtrlRight },
            { Key.LeftAlt, AndroidKeyCode.AltLeft },
            { Key.RightAlt, AndroidKeyCode.AltRight },
            { Key.CapsLock, AndroidKeyCode.CapsLock },
            { Key.NumLock, AndroidKeyCode.NumLock },
            { Key.Scroll, AndroidKeyCode.ScrollLock },

            // Enter / Escape / Backspace / Tab / Space
            { Key.Enter, AndroidKeyCode.Enter },
            { Key.Escape, AndroidKeyCode.Escape },
            { Key.Back, AndroidKeyCode.Del },
            { Key.Delete, AndroidKeyCode.ForwardDel },
            { Key.Tab, AndroidKeyCode.Tab },
            { Key.Space, AndroidKeyCode.Space },

            // Arrows
            { Key.Up, AndroidKeyCode.DpadUp },
            { Key.Down, AndroidKeyCode.DpadDown },
            { Key.Left, AndroidKeyCode.DpadLeft },
            { Key.Right, AndroidKeyCode.DpadRight },

            // Home / End / PageUp / PageDown / Insert
            { Key.Home, AndroidKeyCode.MoveHome },
            { Key.End, AndroidKeyCode.MoveEnd },
            { Key.PageUp, AndroidKeyCode.PageUp },
            { Key.PageDown, AndroidKeyCode.PageDown },
            { Key.Insert, AndroidKeyCode.Insert },

            // Function keys
            { Key.F1, AndroidKeyCode.F1 },
            { Key.F2, AndroidKeyCode.F2 },
            { Key.F3, AndroidKeyCode.F3 },
            { Key.F4, AndroidKeyCode.F4 },
            { Key.F5, AndroidKeyCode.F5 },
            { Key.F6, AndroidKeyCode.F6 },
            { Key.F7, AndroidKeyCode.F7 },
            { Key.F8, AndroidKeyCode.F8 },
            { Key.F9, AndroidKeyCode.F9 },
            { Key.F10, AndroidKeyCode.F10 },
            { Key.F11, AndroidKeyCode.F11 },
            { Key.F12, AndroidKeyCode.F12 }
        };
    }


    public enum AndroidKeyCode
    {
        Unknown = 0,
        SoftLeft = 1,
        SoftRight = 2,
        Home = 3,
        Back = 4,
        Call = 5,
        EndCall = 6,
        Key0 = 7,
        Key1 = 8,
        Key2 = 9,
        Key3 = 10,
        Key4 = 11,
        Key5 = 12,
        Key6 = 13,
        Key7 = 14,
        Key8 = 15,
        Key9 = 16,
        Star = 17,
        Pound = 18,
        DpadUp = 19,
        DpadDown = 20,
        DpadLeft = 21,
        DpadRight = 22,
        DpadCenter = 23,
        VolumeUp = 24,
        VolumeDown = 25,
        Power = 26,
        Camera = 27,
        Clear = 28,
        A = 29,
        B = 30,
        C = 31,
        D = 32,
        E = 33,
        F = 34,
        G = 35,
        H = 36,
        I = 37,
        J = 38,
        K = 39,
        L = 40,
        M = 41,
        N = 42,
        O = 43,
        P = 44,
        Q = 45,
        R = 46,
        S = 47,
        T = 48,
        U = 49,
        V = 50,
        W = 51,
        X = 52,
        Y = 53,
        Z = 54,
        Comma = 55,
        Period = 56,
        AltLeft = 57,
        AltRight = 58,
        ShiftLeft = 59,
        ShiftRight = 60,
        Tab = 61,
        Space = 62,
        Sym = 63,
        Explorer = 64,
        Envelope = 65,
        Enter = 66,
        Del = 67,
        Grave = 68,
        Minus = 69,
        Equals = 70,
        LeftBracket = 71,
        RightBracket = 72,
        Backslash = 73,
        Semicolon = 74,
        Apostrophe = 75,
        Slash = 76,
        At = 77,
        Num = 78,
        HeadsetHook = 79,
        Focus = 80,
        Plus = 81,
        Menu = 82,
        Notification = 83,
        Search = 84,
        MediaPlayPause = 85,
        MediaStop = 86,
        MediaNext = 87,
        MediaPrevious = 88,
        MediaRewind = 89,
        MediaFastForward = 90,
        Mute = 91,
        PageUp = 92,
        PageDown = 93,
        PictSymbols = 94,
        SwitchCharset = 95,
        ButtonA = 96,
        ButtonB = 97,
        ButtonC = 98,
        ButtonX = 99,
        ButtonY = 100,
        ButtonZ = 101,
        ButtonL1 = 102,
        ButtonR1 = 103,
        ButtonL2 = 104,
        ButtonR2 = 105,
        ButtonThumbL = 106,
        ButtonThumbR = 107,
        ButtonStart = 108,
        ButtonSelect = 109,
        ButtonMode = 110,
        Escape = 111,
        ForwardDel = 112,
        CtrlLeft = 113,
        CtrlRight = 114,
        CapsLock = 115,
        ScrollLock = 116,
        MetaLeft = 117,
        MetaRight = 118,
        Function = 119,
        SysRq = 120,
        Break = 121,
        MoveHome = 122,
        MoveEnd = 123,
        Insert = 124,
        Forward = 125,
        MediaPlay = 126,
        MediaPause = 127,
        MediaClose = 128,
        MediaEject = 129,
        MediaRecord = 130,
        F1 = 131,
        F2 = 132,
        F3 = 133,
        F4 = 134,
        F5 = 135,
        F6 = 136,
        F7 = 137,
        F8 = 138,
        F9 = 139,
        F10 = 140,
        F11 = 141,
        F12 = 142,
        NumLock = 143,
        Numpad0 = 144,
        Numpad1 = 145,
        Numpad2 = 146,
        Numpad3 = 147,
        Numpad4 = 148,
        Numpad5 = 149,
        Numpad6 = 150,
        Numpad7 = 151,
        Numpad8 = 152,
        Numpad9 = 153,
        NumpadDivide = 154,
        NumpadMultiply = 155,
        NumpadSubtract = 156,
        NumpadAdd = 157,
        NumpadDot = 158,
        NumpadComma = 159,
        NumpadEnter = 160,
        NumpadEquals = 161,
        NumpadLeftParen = 162,
        NumpadRightParen = 163,
        VolumeMute = 164,
        Info = 165,
        ChannelUp = 166,
        ChannelDown = 167,
        ZoomIn = 168,
        ZoomOut = 169,
        Tv = 170,
        Window = 171,
        Guide = 172,
        Dvr = 173,
        Bookmark = 174,
        Captions = 175,
        Settings = 176,
        TvPower = 177,
        TvInput = 178,
        StbPower = 179,
        StbInput = 180,
        AvrPower = 181,
        AvrInput = 182,
        ProgRed = 183,
        ProgGreen = 184,
        ProgYellow = 185,
        ProgBlue = 186,
        AppSwitch = 187,
        Button1 = 188,
        Button2 = 189,
        Button3 = 190,
        Button4 = 191,
        Button5 = 192,
        Button6 = 193,
        Button7 = 194,
        Button8 = 195,
        Button9 = 196,
        Button10 = 197,
        Button11 = 198,
        Button12 = 199,
        Button13 = 200,
        Button14 = 201,
        Button15 = 202,
        Button16 = 203,
        LanguageSwitch = 204,
        MannerMode = 205,
        Mode3D = 206,
        Contacts = 207,
        Calendar = 208,
        Music = 209,
        Calculator = 210,
        ZenkakuHankaku = 211,
        Eisu = 212,
        Muhenkan = 213,
        Henkan = 214,
        KatakanaHiragana = 215,
        Yen = 216,
        Ro = 217,
        Kana = 218,
        Assist = 219,
        BrightnessDown = 220,
        BrightnessUp = 221,
        MediaAudioTrack = 222,
        Sleep = 223,
        Wakeup = 224,
        Pairing = 225,
        MediaTopMenu = 226,
        Key11 = 227,
        Key12 = 228,
        LastChannel = 229,
        TvDataService = 230,
        VoiceAssist = 231,
        TvRadioService = 232,
        TvTeletext = 233,
        TvNumberEntry = 234,
        TvTerrestrialAnalog = 235,
        TvTerrestrialDigital = 236,
        TvSatellite = 237,
        TvSatelliteBs = 238,
        TvSatelliteCs = 239,
        TvSatelliteService = 240,
        TvNetwork = 241,
        TvAntennaCable = 242,
        TvInputHdmi1 = 243,
        TvInputHdmi2 = 244,
        TvInputHdmi3 = 245,
        TvInputHdmi4 = 246,
        TvInputComposite1 = 247,
        TvInputComposite2 = 248,
        TvInputComponent1 = 249,
        TvInputComponent2 = 250,
        TvInputVga1 = 251,
        TvAudioDescription = 252,
        TvAudioDescriptionMixUp = 253,
        TvAudioDescriptionMixDown = 254,
        TvZoomMode = 255,
        TvContentsMenu = 256,
        TvMediaContextMenu = 257,
        TvTimerProgramming = 258,
        Help = 259,
        NavigatePrevious = 260,
        NavigateNext = 261,
        NavigateIn = 262,
        NavigateOut = 263,
        StemPrimary = 264,
        Stem1 = 265,
        Stem2 = 266,
        Stem3 = 267,
        DpadUpLeft = 268,
        DpadDownLeft = 269,
        DpadUpRight = 270,
        DpadDownRight = 271,
        MediaSkipForward = 272,
        MediaSkipBackward = 273,
        MediaStepForward = 274,
        MediaStepBackward = 275,
        SoftSleep = 276,
        Cut = 277,
        Copy = 278,
        Paste = 279,
        SystemNavigationUp = 280,
        SystemNavigationDown = 281,
        SystemNavigationLeft = 282,
        SystemNavigationRight = 283,
        AllApps = 284
    }

